using System.IO;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEditor;
using UnityEditor.SceneManagement;
using Cinemachine;
namespace BlockNight.Editor {
public static class DemoBuilder {
 static Sprite square,ring,white;static Font font;static Material spriteMat,lineMat;static Transform canvas;
 static Color cyan=new Color(.24f,.96f,.86f),muted=new Color(.40f,.53f,.61f),ink=new Color(.025f,.045f,.08f);
 [MenuItem("Block Night/Build Demo")]
 public static void Build(){
 Directory.CreateDirectory("Assets/BlockNight/Art");Directory.CreateDirectory("Assets/BlockNight/Data");Directory.CreateDirectory("Assets/BlockNight/Scenes");
 white=MakeSprite("UIWhite",5);square=MakeSprite("Square",0);ring=MakeSprite("Ring",4);Sprite diamond=MakeSprite("Diamond",1),triangle=MakeSprite("Triangle",2),disc=MakeSprite("Disc",3);
 font=AssetDatabase.LoadAssetAtPath<Font>("Assets/BlockNight/Fonts/SourceHanSansCN-Regular.otf");
 spriteMat=MaterialAsset("Neon", "Universal Render Pipeline/2D/Sprite-Unlit-Default");lineMat=MaterialAsset("Lines","Sprites/Default");
 var scene=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);
 var root=new GameObject("BLOCK NIGHT — systems");var d=root.AddComponent<GameDirector>();var a=new GameObject("Presentation").AddComponent<ArenaPresentation>();d.arena=a;
 var cfg=AssetDatabase.LoadAssetAtPath<Balance>("Assets/BlockNight/Data/Balance.asset");if(!cfg){cfg=ScriptableObject.CreateInstance<Balance>();AssetDatabase.CreateAsset(cfg,"Assets/BlockNight/Data/Balance.asset");}d.balance=cfg;
 var camera=new GameObject("Main Camera").AddComponent<Camera>();camera.tag="MainCamera";camera.transform.position=new Vector3(0,0,-10);camera.orthographic=true;camera.orthographicSize=7.7f;camera.backgroundColor=new Color(.012f,.021f,.043f);camera.clearFlags=CameraClearFlags.SolidColor;camera.allowHDR=true;camera.gameObject.AddComponent<AudioListener>();camera.gameObject.AddComponent<CinemachineBrain>();camera.GetUniversalAdditionalCameraData().renderPostProcessing=true;
 var vc=new GameObject("Arena Camera — impulse receiver").AddComponent<CinemachineVirtualCamera>();vc.transform.position=camera.transform.position;vc.m_Lens.OrthographicSize=7.7f;vc.m_Lens.Orthographic=true;var receiver=vc.gameObject.AddComponent<CinemachineImpulseListener>();receiver.m_Gain=1;a.impulse=a.gameObject.AddComponent<CinemachineImpulseSource>();a.impulse.m_ImpulseDefinition.m_ImpulseType=CinemachineImpulseDefinition.ImpulseTypes.Uniform;a.impulse.m_ImpulseDefinition.m_ImpulseDuration=.16f;
 var vol=new GameObject("Global Volume — neon + time").AddComponent<Volume>();vol.isGlobal=true;var profile=ScriptableObject.CreateInstance<VolumeProfile>();var bloom=profile.Add<Bloom>(true);bloom.intensity.Override(1.1f);bloom.threshold.Override(.8f);bloom.scatter.Override(.65f);profile.Add<ChromaticAberration>(true).intensity.Override(0);profile.Add<ColorAdjustments>(true).colorFilter.Override(Color.white);profile.Add<Vignette>(true).intensity.Override(.25f);AssetDatabase.CreateAsset(profile,AssetDatabase.GenerateUniqueAssetPath("Assets/BlockNight/Data/NeonVolume.asset"));foreach(var component in profile.components)AssetDatabase.AddObjectToAsset(component,profile);EditorUtility.SetDirty(profile);vol.sharedProfile=profile;a.volume=vol;
 var light=new GameObject("Global Light 2D").AddComponent<Light2D>();light.lightType=Light2D.LightType.Global;light.intensity=.7f;
 var board=new GameObject("BOARD — editable world sprites").transform;
 SpriteObj("Board backing",board,new Vector2(0,0),new Vector2(10.45f,10.45f),new Color(.018f,.04f,.068f),-10);
 for(int x=0;x<11;x++)for(int y=0;y<11;y++)SpriteObj("Tile "+x+" · "+y,board,new Vector2(x-5,y-5),Vector2.one*.87f,new Color(.023f+((x+y)%2)*.004f,.053f,.075f),-9);
 for(int i=0;i<12;i++){float p=-5.5f+i;SpriteObj("Grid vertical "+i,board,new Vector2(p,0),new Vector2(.012f,11),new Color(.04f,.13f,.17f),-8);SpriteObj("Grid horizontal "+i,board,new Vector2(0,p),new Vector2(11,.012f),new Color(.04f,.13f,.17f),-8);}
 for(int i=0;i<4;i++){bool vertical=i<2;SpriteObj("Boundary "+i,board,vertical?new Vector2(i==0?-5.52f:5.52f,0):new Vector2(0,i==2?-5.52f:5.52f),vertical?new Vector2(.035f,11.08f):new Vector2(11.08f,.035f),cyan*1.2f,-7);}
 var lit=MaterialAsset("BoardLit","Universal Render Pipeline/2D/Sprite-Lit-Default");foreach(var tile in board.GetComponentsInChildren<SpriteRenderer>())if(tile.sortingOrder<=-9)tile.sharedMaterial=lit;
 a.playerSprite=SpriteObj("PLAYER — cyan blade",null,Vector2.zero,Vector2.one*.34f,cyan*1.8f,4);a.player=a.playerSprite.transform;SpriteObj("Player core",a.player,Vector2.zero,Vector2.one*.35f,Color.white,5);
 a.trail=a.player.gameObject.AddComponent<TrailRenderer>();a.trail.sharedMaterial=lineMat;a.trail.time=.22f;a.trail.startWidth=.22f;a.trail.endWidth=0;a.trail.startColor=cyan;a.trail.endColor=new Color(cyan.r,cyan.g,cyan.b,0);a.trail.sortingOrder=3;a.trail.minVertexDistance=.05f;
 a.playerLight=new GameObject("Player glow 2D").AddComponent<Light2D>();a.playerLight.lightType=Light2D.LightType.Point;a.playerLight.pointLightOuterRadius=2;a.playerLight.intensity=1.8f;a.playerLight.color=cyan;
 a.shapes=new[]{square,diamond,triangle,disc};a.bodies=new SpriteRenderer[36];a.warnings=new SpriteRenderer[36];a.aims=new LineRenderer[36];var pool=new GameObject("ENEMIES — 36 prebuilt slots").transform;
 for(int i=0;i<36;i++){a.bodies[i]=SpriteObj("Enemy "+i,pool,Vector2.zero,Vector2.one*.48f,Color.red,2);a.warnings[i]=SpriteObj("Warning "+i,pool,Vector2.zero,Vector2.one,Color.red,1);a.warnings[i].sprite=ring;a.bodies[i].enabled=a.warnings[i].enabled=false;var l=new GameObject("Aim "+i).AddComponent<LineRenderer>();l.transform.SetParent(pool);l.sharedMaterial=lineMat;l.startWidth=l.endWidth=.018f;l.sortingOrder=1;l.enabled=false;a.aims[i]=l;}
 a.bullets=new SpriteRenderer[80];var bp=new GameObject("PROJECTILES — 80 prebuilt slots").transform;for(int i=0;i<80;i++){a.bullets[i]=SpriteObj("Shot "+i,bp,Vector2.zero,Vector2.one*.12f,Color.red,3);a.bullets[i].sprite=diamond;a.bullets[i].enabled=false;}
 var ps=new GameObject("Kill shards — Particle System").AddComponent<ParticleSystem>();var main=ps.main;main.playOnAwake=false;main.loop=false;main.startLifetime=.48f;main.startSpeed=3.8f;main.maxParticles=1600;main.simulationSpace=ParticleSystemSimulationSpace.World;var emission=ps.emission;emission.enabled=false;var shape=ps.shape;shape.shapeType=ParticleSystemShapeType.Circle;shape.radius=.06f;var size=ps.sizeOverLifetime;size.enabled=true;size.size=new ParticleSystem.MinMaxCurve(1,AnimationCurve.Linear(0,1,1,0));ps.GetComponent<ParticleSystemRenderer>().sharedMaterial=lineMat;ps.GetComponent<ParticleSystemRenderer>().sortingOrder=8;a.shards=ps;ps.Stop();
 var sound=new GameObject("AUDIO — original synth").AddComponent<SynthAudio>();sound.music=sound.gameObject.AddComponent<AudioSource>();sound.effects=sound.gameObject.AddComponent<AudioSource>();sound.music.playOnAwake=sound.effects.playOnAwake=false;d.audioBus=sound;
 var cg=new GameObject("HUD — editable canvas",typeof(RectTransform),typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster));var c=cg.GetComponent<Canvas>();c.renderMode=RenderMode.ScreenSpaceOverlay;var scaler=cg.GetComponent<CanvasScaler>();scaler.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;scaler.referenceResolution=new Vector2(1600,1000);scaler.matchWidthOrHeight=1;canvas=cg.transform;var h=cg.AddComponent<GameHUD>();d.hud=h;new GameObject("EventSystem",typeof(EventSystem),typeof(StandaloneInputModule));
 Label(canvas,"Brand",new Vector2(145,922),new Vector2(250,110),"方块\n战士",31,cyan);Label(canvas,"Edition",new Vector2(145,851),new Vector2(250,35),"霓虹战术 / 01",12,muted);
 Label(canvas,"Score label",new Vector2(145,720),new Vector2(250,25),"总积分",16,muted);h.score=Label(canvas,"Score",new Vector2(145,679),new Vector2(250,60),"0",36,Color.white);
 Label(canvas,"Time label",new Vector2(145,578),new Vector2(250,25),"生存时间",16,muted);h.time=Label(canvas,"Time",new Vector2(145,540),new Vector2(250,55),"00:00",30,Color.white);
 Label(canvas,"Chain label",new Vector2(145,410),new Vector2(250,25),"连续斩杀",16,muted);h.chain=Label(canvas,"Chain",new Vector2(145,345),new Vector2(250,95),"00",68,cyan);Label(canvas,"Chain hint",new Vector2(145,273),new Vector2(235,55),"转向，延续斩击。\n撞墙，结算连斩。",12,muted);
 Label(canvas,"Upgrade caption",new Vector2(800,959),new Vector2(600,26),"距 离 下 次 强 化",16,cyan,TextAnchor.MiddleCenter);h.countdown=Label(canvas,"Countdown",new Vector2(800,914),new Vector2(350,67),"30.0",46,Color.white,TextAnchor.MiddleCenter);Panel(canvas,"Progress track",new Vector2(800,869),new Vector2(795,5),new Color(.08f,.16f,.2f));h.progress=Panel(canvas,"Kill accelerated progress",new Vector2(800,869),new Vector2(795,5),cyan);h.progress.type=Image.Type.Filled;h.progress.fillMethod=Image.FillMethod.Horizontal;
 Label(canvas,"Temporal label",new Vector2(1430,790),new Vector2(270,25),"时 间 技 能",14,muted);
 Label(canvas,"Slow name",new Vector2(1430,718),new Vector2(270,50),"[ 空格 ]\n时间折叠",21,cyan);h.slowLabel=Label(canvas,"Slow CD",new Vector2(1430,653),new Vector2(270,50),"就绪",29,Color.white);h.slowFill=Panel(canvas,"Slow bar",new Vector2(1420,613),new Vector2(230,4),cyan);h.slowFill.type=Image.Type.Filled;h.slowFill.fillMethod=Image.FillMethod.Horizontal;
 Label(canvas,"Rewind name",new Vector2(1430,516),new Vector2(270,50),"[ Q ]\n时间回溯",21,new Color(.72f,.5f,1));h.rewindLabel=Label(canvas,"Rewind CD",new Vector2(1430,451),new Vector2(270,50),"就绪",25,Color.white);h.rewindFill=Panel(canvas,"Rewind bar",new Vector2(1420,411),new Vector2(230,4),new Color(.72f,.5f,1));h.rewindFill.type=Image.Type.Filled;h.rewindFill.fillMethod=Image.FillMethod.Horizontal;
 Label(canvas,"Risk",new Vector2(1430,266),new Vector2(270,95),"一击即死。\n改写你的时间线。\n\nM / 切换静音",14,muted);
 h.status=Label(canvas,"Status",new Vector2(800,63),new Vector2(950,40),"",17,cyan,TextAnchor.MiddleCenter);h.banner=Label(canvas,"Combo banner",new Vector2(800,118),new Vector2(700,45),"",26,Color.white,TextAnchor.MiddleCenter);
 var hudGroup=Rect("Combat readouts",canvas,new Vector2(800,500),new Vector2(1600,1000));hudGroup.pivot=Vector2.zero;hudGroup.anchoredPosition=new Vector2(-800,-500);var children=new System.Collections.Generic.List<Transform>();foreach(Transform child in canvas)if(child!=hudGroup)children.Add(child);foreach(var child in children)child.SetParent(hudGroup,true);h.readouts=hudGroup.gameObject;
 h.titlePanel=Overlay("Title");Label(h.titlePanel.transform,"Eyebrow",new Vector2(800,746),new Vector2(800,35),"冲 刺 · 连 斩 · 改 写 时 间",16,cyan,TextAnchor.MiddleCenter);Label(h.titlePanel.transform,"Title",new Vector2(800,613),new Vector2(1000,210),"方 块 战 士",88,Color.white,TextAnchor.MiddleCenter);Label(h.titlePanel.transform,"Subtitle",new Vector2(800,489),new Vector2(800,60),"在边缘收刀，在转角改写命运。",21,muted,TextAnchor.MiddleCenter);h.startButton=Button(h.titlePanel.transform,"进入棋盘",new Vector2(800,368),new Vector2(440,70),cyan);h.learnButton=Button(h.titlePanel.transform,"新手引导",new Vector2(800,276),new Vector2(440,60),new Color(.19f,.24f,.34f));Label(h.titlePanel.transform,"Footer",new Vector2(800,137),new Vector2(1000,45),"WASD 移动与转向    /    空格 慢时间    /    Q 回溯",15,muted,TextAnchor.MiddleCenter);
 h.pausePanel=Overlay("Pause");Label(h.pausePanel.transform,"Pause title",new Vector2(800,620),new Vector2(800,100),"时间已暂停",55,Color.white,TextAnchor.MiddleCenter);h.resumeButton=Button(h.pausePanel.transform,"继续战斗 / ESC",new Vector2(800,455),new Vector2(400,70),cyan);
 h.draftPanel=Overlay("Augment selection");Label(h.draftPanel.transform,"Choose title",new Vector2(800,794),new Vector2(1000,100),"突 破 极 限",48,Color.white,TextAnchor.MiddleCenter);Label(h.draftPanel.transform,"Choose hint",new Vector2(800,714),new Vector2(1000,45),"选择一项强化 / 点击卡片或按 1 · 2 · 3",16,cyan,TextAnchor.MiddleCenter);h.cards=new Button[3];h.cardTexts=new Text[3];for(int i=0;i<3;i++){h.cards[i]=Button(h.draftPanel.transform,"",new Vector2(400+i*400,467),new Vector2(365,375),new Color(.075f,.14f,.2f));h.cardTexts[i]=h.cards[i].GetComponentInChildren<Text>();h.cardTexts[i].fontSize=21;h.cardTexts[i].color=Color.white;}
 h.deathPanel=Overlay("Run ended");Label(h.deathPanel.transform,"Death title",new Vector2(800,734),new Vector2(900,100),"时间线终结",60,new Color(1,.35f,.43f),TextAnchor.MiddleCenter);h.deathScore=Label(h.deathPanel.transform,"Run stats",new Vector2(800,550),new Vector2(700,210),"",25,Color.white,TextAnchor.MiddleCenter);h.retryButton=Button(h.deathPanel.transform,"再战一次",new Vector2(800,361),new Vector2(450,70),cyan);h.homeButton=Button(h.deathPanel.transform,"返回主界面",new Vector2(800,267),new Vector2(450,60),new Color(.19f,.24f,.34f));
 h.tutorialPanel=Panel(canvas,"Tutorial",new Vector2(800,155),new Vector2(850,110),new Color(.025f,.06f,.095f,.97f)).gameObject;h.tutorialText=Label(h.tutorialPanel.transform,"Lesson",new Vector2(0,8),new Vector2(800,85),"",18,Color.white,TextAnchor.MiddleCenter,true);h.skipButton=Button(canvas,"跳过教学",new Vector2(1440,130),new Vector2(220,45),new Color(.12f,.2f,.24f));
 // Skip button belongs to tutorial visibility, preserving its intended screen position.
 h.skipButton.transform.SetParent(h.tutorialPanel.transform,true);
 h.pausePanel.SetActive(false);h.draftPanel.SetActive(false);h.deathPanel.SetActive(false);h.tutorialPanel.SetActive(false);
 PlayerSettings.runInBackground=true;PlayerSettings.colorSpace=ColorSpace.Linear;PlayerSettings.defaultScreenWidth=1600;PlayerSettings.defaultScreenHeight=1000;
 EditorSceneManager.SaveScene(scene,"Assets/BlockNight/Scenes/BlockNight.unity");EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene("Assets/BlockNight/Scenes/BlockNight.unity",true)};AssetDatabase.SaveAssets();Debug.Log("BLOCK NIGHT: editable demo scene built.");
 }
 static Material MaterialAsset(string name,string shader){string p="Assets/BlockNight/Art/"+name+".mat";var m=AssetDatabase.LoadAssetAtPath<Material>(p);if(!m){m=new Material(Shader.Find(shader));AssetDatabase.CreateAsset(m,p);}return m;}
 static Sprite MakeSprite(string name,int shape){string p="Assets/BlockNight/Art/"+name+".png";var t=new Texture2D(64,64);for(int y=0;y<64;y++)for(int x=0;x<64;x++){float u=(x-31.5f)/30,v=(y-31.5f)/30;float r=Mathf.Sqrt(u*u+v*v);bool on=shape==5?true:shape==0?Mathf.Max(Mathf.Abs(u),Mathf.Abs(v))<1:shape==1?Mathf.Abs(u)+Mathf.Abs(v)<1:shape==2?v>-.85f&&v<.95f&&Mathf.Abs(u)<(.95f-v)*.55f:shape==3?r<1:r<1&&r>.92f;t.SetPixel(x,y,on?Color.white:Color.clear);}t.Apply();File.WriteAllBytes(p,t.EncodeToPNG());Object.DestroyImmediate(t);AssetDatabase.ImportAsset(p);var imp=(TextureImporter)AssetImporter.GetAtPath(p);imp.textureType=TextureImporterType.Sprite;imp.spritePixelsPerUnit=64;imp.alphaIsTransparency=true;imp.mipmapEnabled=false;imp.SaveAndReimport();return AssetDatabase.LoadAssetAtPath<Sprite>(p);}
 static SpriteRenderer SpriteObj(string name,Transform parent,Vector2 pos,Vector2 size,Color color,int order){var g=new GameObject(name);g.transform.SetParent(parent,false);g.transform.localPosition=pos;g.transform.localScale=new Vector3(size.x,size.y,1);var r=g.AddComponent<SpriteRenderer>();r.sprite=square;r.sharedMaterial=spriteMat;r.color=color;r.sortingOrder=order;return r;}
 static RectTransform Rect(string name,Transform parent,Vector2 pos,Vector2 size,bool relative=false){var g=new GameObject(name,typeof(RectTransform));var r=g.GetComponent<RectTransform>();r.SetParent(parent,false);r.anchorMin=r.anchorMax=relative?new Vector2(.5f,.5f):Vector2.zero;r.pivot=new Vector2(.5f,.5f);if(parent==canvas){r.anchorMin=r.anchorMax=new Vector2(.5f,.5f);pos-=new Vector2(800,500);}r.anchoredPosition=pos;r.sizeDelta=size;return r;}
 static Image Panel(Transform parent,string name,Vector2 pos,Vector2 size,Color color){var r=Rect(name,parent,pos,size);var im=r.gameObject.AddComponent<Image>();im.sprite=white;im.color=color;im.raycastTarget=false;return im;}
 static Text Label(Transform parent,string name,Vector2 pos,Vector2 size,string value,int fs,Color color,TextAnchor anchor=TextAnchor.MiddleLeft,bool relative=false){var r=Rect(name,parent,pos,size,relative);var t=r.gameObject.AddComponent<Text>();t.font=font;t.fontSize=fs;t.text=value;t.color=color;t.alignment=anchor;t.supportRichText=true;t.verticalOverflow=VerticalWrapMode.Overflow;t.raycastTarget=false;return t;}
 static Button Button(Transform parent,string name,Vector2 pos,Vector2 size,Color color){var im=Panel(parent,name,pos,size,color);im.raycastTarget=true;var b=im.gameObject.AddComponent<Button>();b.targetGraphic=im;im.gameObject.AddComponent<ButtonFeel>();Label(im.transform,"Label",Vector2.zero,size-new Vector2(30,15),name,18,color==cyan?ink:Color.white,TextAnchor.MiddleCenter,true);return b;}
 static GameObject Overlay(string name){var g=Panel(canvas,name,new Vector2(800,500),new Vector2(2000,1300),new Color(.012f,.025f,.048f,.96f)).gameObject;var r=g.GetComponent<RectTransform>();r.pivot=Vector2.zero;r.anchoredPosition=new Vector2(-800,-500);r.sizeDelta=new Vector2(1600,1000);g.GetComponent<Image>().raycastTarget=true;return g;}
}
}
